name: generate-lists

on:
  push:
    branches: [ main ]
    paths: [ 'lists/*.list' ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Sort main list
        run: |
          for l in lists/*.list; do
            sort -uo "$l"{,}
            sed -i '1{/^ *$/d}'
          done

      - name: Generate app-specific lists
        run: python lists/generate.py

      - name: Commit and push
        run: |
          git config user.name 'GitHub Actions bot'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -am "Update lists"
          git push
