name: generate-lists

on:
  push:
    branches: [ main ]
    paths: [ 'lists/*.list' ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          python lists/generate.py
          git config user.name 'GitHub Actions bot'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -am "Update lists"
          git push
